#!/usr/bin/env bash

set -eo pipefail

echo "RUN: noteshrink ${*}"

output=out

while true; do
  case "${1}" in
  -b)
    output=${2}
    shift 2
    ;;
  -c)
    shift 2
    ;;
  *)
    break
    ;;
  esac
done

for (( i=1; i <= "${#}"; i++ )); do
    fn=$(printf "%s%0002i.png" "${output}" ${i})
    echo "shrinking ${!i} -> ${fn}"
    cat "${!i}" > "${fn}"
    echo "(shrunk)" >> "${fn}"
done

sleep $(( RANDOM & 0x3 ))